apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: simoc-backend-config
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 50