language: python
python:
  - "3.2"
  - "3.3"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  # * E501 - line length limit
  # * E123 - indentation on data structures
  - nosetests --with-coverage --cover-package=mesa
  # - ./tests/test_end_to_end_viz.sh  # needs to be investigated on why this took forever
after_success:
  - coveralls
branches:
  only:
    - master
