language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  # * E501 - line length limit
  # * E123 - indentation on data structures
  - python run_tests.py
after_success:
  - coveralls
branches:
  only:
    - master
