language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  # * E501 - line length limit
  # * E123 - indentation on data structures
  - nosetests --with-coverage --cover-package=simoc_server
after_success:
  - coveralls
branches:
  only:
    - master
