version: '3'
services:
  redis:
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    image: "redis"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./sqlite:/simoc/sqlite
    depends_on:
      - redis
  flask-app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      WSGI_WORKERS: ${WSGI_WORKERS}
      APP_PORT: ${APP_PORT}
    volumes:
      - ./sqlite:/simoc/sqlite
    depends_on:
      - redis
