version: '3.6'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
      - '${HTTPS_PORT}:${HTTPS_PORT}'
    networks:
      - simoc-net
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx/simoc_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/proxy_ws_params:/etc/nginx/proxy_ws_params
      - ./certs:/etc/nginx/certs
    depends_on:
      - flask-app
    deploy:
      replicas: 1
  simoc-db:
    image: mysql/mysql-server
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - simoc-net
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    deploy:
      replicas: 1
  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - simoc-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    deploy:
      replicas: 1
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    image: 127.0.0.1:5000/celery-worker
    restart: always
    networks:
      - simoc-net
    healthcheck:
      test: ['CMD', 'bash', 'ping_worker.sh']
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/simoc
    depends_on:
      - simoc-db
      - redis
    deploy:
      replicas: ${CELERY_WORKERS}
      resources:
        limits:
          cpus: '.5'
          memory: 300M
  flask-app:
    build: .
    image: 127.0.0.1:5000/flask-app
    restart: always
    ports:
      - 8080
    networks:
      - simoc-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/ping']
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FLASK_SECRET: ${FLASK_SECRET}
    volumes:
      - .:/simoc
    depends_on:
      - simoc-db
      - redis
    deploy:
      replicas: ${FLASK_WORKERS}
      resources:
        limits:
          cpus: '.2'
          memory: 300M

volumes:
  db-data: {}

networks:
  simoc-net:
    driver: overlay
    attachable: true
