version: '3.6'
services:
  frontend-dev:
    build:
      context: ${DEV_FE_DIR}
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/frontend-dev
    restart: always
    ports:
      #- '${HTTP_PORT}:${HTTP_PORT}'
      - 8080:8080
    networks:
      - simoc-net
    volumes:
      - '${DEV_FE_DIR}:/frontend'
    depends_on:
      - nginx
