version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - simoc-net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  simoc-db:
    image: mysql/mysql-server
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - simoc-net
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    networks:
      - simoc-net
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis-replica:
    image: bitnami/redis:latest
    ports:
      - 6379
    networks:
      - simoc-net
    depends_on:
      - redis
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    image: 127.0.0.1:5000/celery-worker
    networks:
      - simoc-net
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/simoc
    depends_on:
      - simoc-db
      - redis
      - redis-replica
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 200M
  flask-app:
    build: .
    image: 127.0.0.1:5000/flask-app
    ports:
      - 8080
    networks:
      - simoc-net
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/simoc
    depends_on:
      - simoc-db
      - redis
      - redis-replica
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 200M
networks:
  simoc-net:
