apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simoc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simoc
        track: stable
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=simoc-213717:us-central1:simoc=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: simoc
          image: gcr.io/simoc-213717/simoc@sha256:d4d36fe2ee746fc8ccd390cc894b893565f1b6a0c6413fc8368bd4b89d453b35
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: "500M"
              cpu: 1.0
            limits:
              memory: "1G"
              cpu: 2.0
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
