apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: simoc-celery-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simoc-celery-cluster
  minReplicas: 10
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
