apiVersion: apps/v1
kind: Deployment
metadata:
  name: simoc-flask-server
  labels:
    app: simoc-flask-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simoc-flask-server
  template:
    metadata:
      labels:
        app: simoc-flask-server
        track: stable
    spec:
      containers:
        - name: simoc-flask-server
          image: gcr.io/<PROJECT_ID>/simoc_flask:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 30
          env:
          - name: DB_TYPE
            valueFrom:
              configMapKeyRef:
                name: simoc-db-config
                key: db_type
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: simoc-db-config
                key: db_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: simoc-db-config
                key: db_port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: simoc-db-config
                key: db_name
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: simoc-db-config
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: simoc-db-creds
                key: db_password
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: redis_host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: redis_port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-creds
                key: redis_password
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "300M"
              cpu: .2
            limits:
              memory: "500M"
              cpu: .5
